name: 'Patcher Action'
description: 'Guithub Action for Patcher'
author:  'info@gruntwork.io'
outputs:
  patcher_action_updates:
    description: "Dependencies Updates"
    value: ${{ steps.random-number-generator.outputs.random-number }}
  patcher_action_manual_steps:
    description: "Manual Steps"
runs:
  using: "composite"
  steps:
    - run: main.sh
      shell: bash
